### ISSUE TITLE
Quote Detail

### ISSUE THREAD

**Issue by tonilopezmr** [srgtrujillo/quotes#2]
When click y any Quote should see the Quote text and author.

**Comment by tonilopezmr** [comment]
C'mon @srgtrujillo create a Quote Detail !!!!!!!

Think that Quote Detail isn't need a `presenter`,  `usecase`, etc...

@srgtrujillo Why?? `<_(°_°)_>`

**Comment by srgtrujillo** [comment]
Hi @tonilopezmr, I think too that Quote Detail isn't need a `presenter`, `usecase`, etc, because at this moment the application has not more functionality. If we need to implement the feature to put likes doing click on likes image, I think this detail view will need be managed by a `presenter` that uses this `use case`. Do you agree?

I used some material design on QuoteDetailActivity 😜:

![app](https://cloud.githubusercontent.com/assets/15813309/18222270/a7dab306-7192-11e6-9d57-b877150c650f.gif)

**Comment by tonilopezmr** [comment]
Where is your commits?

How do you share the information from list to detail activity?

Of course, the detail needs a presenter to do likes.

**Comment by srgtrujillo** [comment]
At first, I thought implement the interface parcelable in the class Quote, but if I do that, the domain layer is dependent of the Android layer. One of the goals of the MVP architecture is to abstract the application domain of the framework used, right? Well, what I have done has been to pass the attributes of the class Quote separately, using the basic intent extras, but I don't know if it is the better way to do this. I suppose that in this case is when you need to use the ViewModels.

**Comment by tonilopezmr** [comment]
Right, you have two differents ways, by bundle argument or parcelable, but parcelabe you need a viewmodel, etc... In this case at the moment by bundle is correct, but if you want parcelable is better.

**Comment by srgtrujillo** [comment]
Ok, thank you very much. It's a pleasure doing business with you!! 😄
